apiVersion: v1
kind: Secret
metadata:
  name: "sys-password"
type: Opaque
stringData:
  accounts.json: |-
    accounts: {
      SYS: {
        users: [
          {user: admin, password: {{ randAlphaNum 32 }}}
        ]
      },
    }
    system_account: SYS
