{{- $secret := (lookup "v1" "Secret" .Release.Namespace "eventing-nats-accounts") -}}
apiVersion: v1
kind: Secret
metadata:
  name: eventing-nats-accounts
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
{{ if $secret -}}
data:
  accountsJson: {{ $secret.data.accountsJson }}
{{ else -}}
{{ $newPassword := (randAscii 30) }}
stringData:
  accountsJson: |-
    accounts: {
      SYS: {
        users: [
          {user: admin, password: {{ $newPassword }}}
        ]
      },
    }
    system_account: SYS
{{ end }}
