{{- $secretName := printf "%s-%s" (include "nats.fullname" . ) "-secret" -}}
{{- $oldSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
{{ if $oldSecret -}}
data:
  accountsJson: {{ $oldSecret.data.accountsJson }}
{{ else -}}
{{ $newPassword := (randAlphaNum 30) }}
stringData:
  accountsJson: |-
    accounts: {
      SYS: {
        users: [
          {user: admin, password: {{ $newPassword }}}
        ]
      },
    }
    system_account: SYS
{{ end }}
