apiVersion: v1
kind: Secret
metadata:
  name: "eventing-nats-system-events"
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "sys-password") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $jwtSecret to existing secret data or generate a random one when not exists
  {{- $sysSecret := (get $secretData "sys-password") | default (randAlphaNum 32 | b64enc) }}
  sys-password: {{ $sysSecret | quote }}
